# Generated by Django 5.0.14 on 2025-05-22 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_photocomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='photocomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
