# Generated by Django 5.0.14 on 2025-05-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_rename_photo_id_photocomment_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='photo',
            new_name='photo_id',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='user',
            new_name='user_id',
        ),
    ]
