# Generated by Django 5.0.14 on 2025-05-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_rename_photo_photocomment_photo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocomment',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
