# Generated by Django 5.0.14 on 2025-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_photocomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
